### PR TITLE
Update Gradle Command for Supporting Latest Android Studio Version

### PR DESCRIPTION
**Pull request by farhanpahlevi**
I made some changes for supporting latest Android Studio version (thanks for scheduled sharing session), here's list of changes : 
- Refine Gradle structure, centralize dependencies
- Update `compile` (already deprecated) to `implementation` and `api`
- Bump Gradle build tools using v`3.6.4`
- Bump Gradle version to `5.6.4`
- Adding some todo for replace fabric crashlytics to firebase crashlytics in demo app
- Remove empty test

**Please test this implementation first before deciding to merge** it or no, just test publish the Artifact locally or something like that, in my machine I succeed publish it to mavenlocal, you can check the artifact in `/Users/<user_name>/.m2/repository/com/midtrans/`.

### CODE REVIEW

**Review by femmerling — APPROVED** [review]
Thanks for this @farhanpahlevi 
LGTM

**Comment by askur87** [comment]
LGTM

**Review by askur87 — COMMENTED** [review]
LGTM

**Review by uziwuzzy — APPROVED** [review]

**Review by femmerling — APPROVED** [review]
LGTM

**Pull request merged**
